### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by florianschmidt1994** [kiliankoe/dvbjs#12]
Changes on 'master' should be published to npm as well. A system needs to be established when to publish to npm, e.g. with each increase in version number?

**Comment by kiliankoe** [comment]
I've been trying to publish each tagged update here. But I already wanted to add both of you as maintainers to this project on npmjs as well. Is that ok with you?

**Comment by florianschmidt1994** [comment]
Yes very much ok with me.

**Comment by kiliankoe** [comment]
Might as well add both of you as contributors to the package.json as well. Mind filling in the info with your name, email and if you want a url?

**Comment by rebugger** [comment]
Also fine with me, thank you

**Comment by florianschmidt1994** [comment]
No problem. For the url just use https://github.com/florianschmidt1994

**Comment by kiliankoe** [comment]
I meant it more along the lines of "Go ahead and add yourself" :D

**Comment by florianschmidt1994** [comment]
Issue closed:
* Data of contributors is now in package.json
* package.json is on branch master after I did `git cherry-pick`
