### ISSUE TITLE
Additional VVO endpoints

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbjs#19]
Just stumbled across these:

`http://widgets.vvo-online.de/abfahrtsmonitor/Haltestelle.do?ort=dresden&hst=helmhol`

``` json
[
    [
        ["Dresden"]
    ],
    [
        ["Helmholtzstraße", "Dresden", "33000742"]
    ]
]
```

Seems to exist for auto-completion and the like. I'm guessing the number is an ID? No clue though.

---

`http://widgets.vvo-online.de/abfahrtsmonitor/Verkehrsmittel.do`

``` json
[
    ["AST/Rufbus", "Rufbus"],
    ["Fähre", "Fähre"],
    ["Regionalbus", "Regionalbus"],
    ["S-Bahn", "S-Bahn"],
    ["Seil-/Schwebebahn", "Seil-/Schwebebahn"],
    ["Stadtbus", "Stadtbus"],
    ["Straßenbahn", "Straßenbahn"],
    ["Zug", "Zug"]
]
```

Unfortunately doesn't seem to support `hst`, which would make this rather cool. Just seems to be a list of all means of transportation existing somewhere within the network of the VVO.

**Comment by ronhippler** [comment]
this is for selecting allowed means of transport:

[`http://widgets.vvo-online.de/abfahrtsmonitor/Abfahrten.do?ort=Dresden&hst= hbf&vz=10&vm=S-Bahn,Zug&lim=15&timestamp=1453355390879&iso=1`](http://widgets.vvo-online.de/abfahrtsmonitor/Abfahrten.do?ort=Dresden&hst= hbf&vz=10&vm=S-Bahn,Zug&lim=15&timestamp=1453355390879&iso=1)

will only show trains. the departure itself does not include the transport type.

**Comment by kiliankoe** [comment]
Very cool, thanks! Do you know of any additional docs regarding widgets.vvo-online.de?

**Comment by ronhippler** [comment]
Additional? No.

**Comment by ronhippler** [comment]
i added the transport type for stop pins. see a915a7fd81d9583afa8a209982d86e0ec087678d
