### ISSUE TITLE
gh-pages Abfahrtsmonitor

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbjs#26]
Not really part of this package, but it'd be kinda cool to run this on a gh-pages branch styled like this would be: https://www.dvb.de/de-de/service/geschaeftskunden/abfahrtsmonitor/

**Comment by ronhippler** [comment]
would be cleaner as a second repo

**Comment by kiliankoe** [comment]
Yeah, you're probably right^^
