### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbjs#27]
*dvb*js might not have been the wisest choice to go with, albeit being pretty descriptive for its use-case. I'm currently on the lookout for alternatives, especially in regard to an upcoming TRIAS migration. This should influence all client libraries possibly involving a move to a new github organization as well.

The best option would be going with something that's not specific to a single provider, like the VVO (or the DVB underneath that). I'm pretty sure the name TRIAS is trademarked and something close to IP-KOM-ÖV is neither internationally compatible nor *sexy* 😄 

There's also [public-transport-enabler](https://github.com/schildbach/public-transport-enabler), which is however built on top of EFA afaik, so it's not necessarily the same idea. 

Or would it be a wise choice to keep the current implementations and start over entirely?

Any suggestions?

**Comment by dirkonet** [comment]
Maybe just change what DVB stands for?
* Daten von Bussen(&Bahnen)
* Digital VVO Bridge

**Comment by kiliankoe** [comment]
I like the first one^^ "Digital VVO Bridge" however wouldn't be a good fit, since ideally this would go further than a single provider.

**Comment by dirkonet** [comment]
* Digital Verkehrsbetriebe Bridge
* VBD: VerkehrsBetriebeDaten
* DVB: DatenVerkehrsBetrieb
* DVB: Daten von Verkehrs-Betrieben

**Comment by florianschmidt1994** [comment]
I actually like (Elon Musks take on acronyms)[https://mannerofspeaking.org/2015/12/17/acronyms-can-seriously-suck/] and would like to see a new name that is not an acronym. I don't have any ideas though  ¯\_(ツ)_/¯

**Comment by dirkonet** [comment]
In the tradition of taking already existing words to make sure you never find what you are looking for on the search engine of your choice (see Swift, Python,…), how about Bus?

**Comment by kiliankoe** [comment]
I'm currently thinking about going with *Triassic*, the english term for the time period which is called "Trias" in German.

**Comment by florianschmidt1994** [comment]
![](http://i.giphy.com/n5FovccDXbcOY.gif)
Triassic park 😄

**Comment by kiliankoe** [comment]
I think I'd also prefer going with rewrites of the existing libraries and keeping the current stuff around, just removing EFA as soon as that is gone.

This is going to be fun^^

**Comment by kiliankoe** [comment]
Since I've already started having fun with a new swift lib and a repo for a js version at least exists, I guess this can be closed.

See https://github.com/triassic-park for more 🙃
