### ISSUE TITLE
'arrivalTime' is not outputting the correct time

### ISSUE THREAD

**Issue by jens-maus** [kiliankoe/dvbjs#28]
When doing a "monitor" request the outputted 'arrivalTime' is not the absolute time a certain transportation system arrives but seems to be the actual request time as can even be seen in the example of the README file itself because the "arrivalTimeRelative" is always different but the "arrivalTime" always almost the same output.

**Comment by kiliankoe** [comment]
Oh, seems to be a rather unfortunate oversight. Looks like nobody's been using that property 😉 

Looks like there was a wrong factor in there, I'll go and fix that right away. Thanks for the issue!

**Comment by kiliankoe** [comment]
Just published the fix to npm as 4.2.1.
