### ISSUE TITLE
Include actual date/time in the json return

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbjs#3]
The format

```js
{
  line: "11",
  direction: "Zschertnitz",
  arrivaltime: 8
}
```

is somewhat unsatisfying in that the arrivaltime might be more easily used as an actual js date parseable string. Same goes for the times in the routes.

**Comment by rebugger** [comment]
Keeping a relative time might still be useful since no further calculation is needed.
Maybe this format is the best of both worls:
```js
{
  line: "11",
  direction: "Zschertnitz",
  arrivalTimeRelative: 8,
  arrivalTime: "Wed, 24 Jun 2015 20:01:40 GMT"
}
```

**Comment by kiliankoe** [comment]
Probably the best idea...
