### ISSUE TITLE
.route is not working

### ISSUE THREAD

**Issue by ronhippler** [kiliankoe/dvbjs#38]
> StatusCodeError: 404 - The specified URL cannot be found.

this method uses the XML request and is failing for both vvo-online and faplino.

**Comment by kiliankoe** [comment]
EFA was supposed to be shut down at some point in the near future, but that'd be kinda fast no matter what...

**Comment by ronhippler** [comment]
im already working on a solution with the dvb mobile api

**Comment by kiliankoe** [comment]
\o/

**Comment by artifactdev** [comment]
Hopefully this will be merged soon 'cause routes stopped working for my alexa Skill

**Comment by artifactdev** [comment]
@ronhippler  Are you able to wrap .route() so origin and destination can have names like the old way and .route is searching for there ids to search for route?

**Comment by ronhippler** [comment]
the problem is, that the names are not unique. In most cases you will get a route for other stations or places you wanted.

**Comment by artifactdev** [comment]
Any news on this?

**Comment by rtwalz** [comment]
Will .route be coming back soon?

**Comment by kiliankoe** [comment]
I haven't had any time and resources to work on this for quite some while now and I'm guessing it's very similar for @ronhippler. The good news though is that the VVO's WebAPI seems to be rather functional and I haven't been getting any false positives when searching for station names from another project using another library, so that should be easy to implement here as well.

PRs are gladly accepted! 😊

**Comment by rtwalz** [comment]
Great, will probably make a PR then with the mobile API. Starting to work on a telegram bot for routing and maps, and this library helps a lot 😄

**Comment by kiliankoe** [comment]
Please add your telegram bot to [kiliankoe/vvo](https://github.com/kiliankoe/vvo) when done, I'd love to use it! 😄 There's a few out there already, including [@DVBManniBot](https://t.me/DVBManniBot) and [@oepnvdresdenbot](https://t.me/oepnvdresdenbot) although the latter still has quite a few bugs for me to iron out 🙈
