### ISSUE TITLE
dvb.find() and dvb.monitor() returning undefined for some stop searches

### ISSUE THREAD

**Issue by jens-maus** [kiliankoe/dvbjs#40]
Something just changed here last night. Please have a look at the following:

```
> dvb.find("Körnerplatz", function(err, data) { console.log(data); });
> undefined
```

But the following works:

```
> dvb.find("Körnerplat", function(err, data) { console.log(data); });
> [ { stop: 'Körnerplatz',
    id: '33000832',
    city: 'Dresden',
    coords: [ 51.05411984235784, 13.814664768428816 ] },
  { stop: 'Körnerplatz',
    id: '36080103',
    city: 'Döbeln',
    coords: [ 51.1189877898748, 13.118164070373634 ] },
  { stop: 'Körnerplatz-Schule',
    id: '36080155',
    city: 'Döbeln',
    coords: [ 51.117933714936974, 13.118409987591615 ] } ]
```

Please note that I simply removed the `z` at the end of "Körnerplatz" to actually find a match.  Also note please that the following strange search requests also find a match:

using `Koernerplatz`:
```
> dvb.find("Koernerplatz", function(err, data) { console.log(data); });
> [ { stop: 'Körnerplatz',
    id: '33000832',
    city: 'Dresden',
    coords: [ 51.05411984235784, 13.814664768428816 ] },
  { stop: 'Körnerplatz',
    id: '36080103',
    city: 'Döbeln',
    coords: [ 51.1189877898748, 13.118164070373634 ] },
  { stop: 'Körnerplatz-Schule',
    id: '36080155',
    city: 'Döbeln',
    coords: [ 51.117933714936974, 13.118409987591615 ] } ]
```

using 'Kornerplatz' (no umlaut:
```
> dvb.find("Kornerplatz", function(err, data) { console.log(data); });
> [ { stop: 'Körnerplatz',
    id: '33000832',
    city: 'Dresden',
    coords: [ 51.05411984235784, 13.814664768428816 ] },
  { stop: 'Körnerplatz',
    id: '36080103',
    city: 'Döbeln',
    coords: [ 51.1189877898748, 13.118164070373634 ] },
  { stop: 'Körnerplatz-Schule',
    id: '36080155',
    city: 'Döbeln',
    coords: [ 51.117933714936974, 13.118409987591615 ] },
  { stop: 'Tzschirnerplatz',
    id: '36060419',
    city: 'Mittweida',
    coords: [ 50.986900674158946, 12.976825926925255 ] } ]
```

Please that this even matches stops in Mittweida where just "platz" is a real match in the search string?!?!

So do you guys know if the VVO changed something last night regarding the search syntax? I find it quite awkward how searches work now and find it especially strange that a direct match for `Körnerplatz` doesn't work at all anymore?!?!

**Comment by kiliankoe** [comment]
Looks like this behavior can be replicated in the mobile app (which is the primary user of the WebAPI). At least I think it can, since the app's usability is *questionable*. But the completion not showing up on trying to search for a stop by its full name is imo a bug that can be reported to the VVO. Might be best to focuse on the mobile app though, since usage of the WebAPI for other stuff isn't in any way supported.

**Comment by kiliankoe** [comment]
Submitted the following feedback via the app.

> Seit gestern scheint die Autovervollständigung der Suche keine Resultate mehr zu liefern, wenn ich den vollen Namen einer Haltestelle eingebe. Ist dies gewolltes Verhalten? Die App lässt mich dann leider nicht mit meiner Suche fortfahren. 
Beispiel: Eingabe "Körnerplat" liefert Resultate. Eingabe von "Körnerplatz" nicht. Alternativschreibweisen wie "Koernerplatz" und "Kornerplatz" funktionieren ebenso. Nur der korrekte Name nicht.

**Comment by kiliankoe** [comment]
Btw: This is the WebAPI's response in that case:

```js
{
  "ResponseStatus": {
    "ErrorCode": "ArgumentException",
    "Message": "Die angegebene DateTime stellt eine ungültige Zeit dar. Wenn die Uhr beispielsweise vorgestellt wird, ist jede Uhrzeit innerhalb des übersprungenen Zeitraums ungültig.\r\nParametername: dateTime"
  }
}
```

There's no `dateTime` or other date param in the request. Definitely looks like a bug on their side.
