### ISSUE TITLE
Bubble up API errors

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/dvbjs#41]
The WebAPI outputs errors on malformed requests. It would probably make sense to bubble these up as well so that a user of dvbjs doesn't just get an `undefined` to work with.

Somewhat related: #40

Example:

```js
{
  "ResponseStatus": {
    "ErrorCode": "ArgumentException",
    "Message": "Die angegebene DateTime stellt eine ungültige Zeit dar. Wenn die Uhr beispielsweise vorgestellt wird, ist jede Uhrzeit innerhalb des übersprungenen Zeitraums ungültig.\r\nParametername: dateTime"
  }
}

{
  "Status": {
    "Code": "ValidationError",
    "Message": "time has to be a valid time in the future"
  }
}

{
  "Status": {
    "Code": "ValidationError",
    "Message": "stopid has to be not null and must be a number"
  }
}
```

**Comment by ronhippler** [comment]
maybe we could throw errors, so the catch of the promises could be used to handle the errors. or do you wand to return a json error field?

**Comment by kiliankoe** [comment]
Throwing errors feels like a reasonable thing to do in JS-land these days. Would it still be possible to stay compatible with promises *and* callbacks somehow?
