### ISSUE TITLE
coords() returns wrong coordinates

### ISSUE THREAD

**Issue by ronhippler** [kiliankoe/dvbjs#47]
Postplatz (13.733525449482327, 51.050838947163165) returns 5656699|4621216 which is projected into (-30.43983230459976, 51.24502510250834)

maybe they do not use GK4 anymore?

**Comment by kiliankoe** [comment]
Looks like they're actually using (correct) GK5 now :O Never thought I'd live to see the day.

**Comment by ronhippler** [comment]
FYI: They are using two the Web Mercator projection for some but not all requests.
