### ISSUE TITLE
Please add the StopID to ILocation

### ISSUE THREAD

**Issue by Beiri22** [kiliankoe/dvbjs#49]
in order to directly reuse a stop from any route.

Whenever you want to use a specific stop, you need its ID. It's a common use case to navigate to the stop monitoring view based any stop shown in the currently active route. Without the stop's id you'd have to perform another search for the stop id based on its name. This is now unnecessary.

**Comment by ronhippler** [comment]
It's added and released. Good things come to those who wait. Sry for that.
