### ISSUE TITLE
Use git-flow for further commits

### ISSUE THREAD

**Issue by rebugger** [kiliankoe/dvbjs#9]
I have the following method in mind:
* use _master_ as release-branch
* set _develop_ as default branch
* split up methods in dvbjs.js into multiple files (as currently done in _develop_) for easier merging

**Comment by florianschmidt1994** [comment]
How do we continue on this issue? If we really want to use git flow i would recommend following this guide http://danielkummer.github.io/git-flow-cheatsheet/ and closing this issue for now?

**Comment by rebugger** [comment]
Sounds good for me. If I find the time (maybe next week) I'll do some of the needed changes.
I'll close this issue.
